version: '3'

tasks:
    start:
        cmds:
            - npm run dev
        desc: Start the development server
    build:
        cmds:
            - npm run build
        desc: Build the project
