import { Modes } from '../types';

export const CONTROL_TO_PARAM_MAPS = {
    [Modes.OPL]: {
        slider1: 'operators[0].tl',
        slider2: 'operators[1].tl',
        slider3: 'operators[2].tl',
        slider4: 'operators[3].tl',
        slider5: 'fb',
        knob1: 'operators[0].mult',
        knob2: 'operators[1].mult',
        knob3: 'operators[2].mult',
        knob4: 'operators[3].mult',
        knob5: 'operators[0].ws',
        knob6: 'operators[1].ws',
        knob7: 'operators[2].ws',
        knob8: 'operators[3].ws',
    },
    [Modes.OPM]: {
        slider1: 'operators[0].tl',
        slider2: 'operators[1].tl',
        slider3: 'operators[2].tl',
        slider4: 'operators[3].tl',
        slider5: 'fb',
        knob1: 'operators[0].mul',
        knob2: 'operators[1].mul',
        knob3: 'operators[2].mul',
        knob4: 'operators[3].mul',
        knob5: 'operators[0].ws',
        knob6: 'operators[1].ws',
        knob7: 'operators[2].ws',
        knob8: 'operators[3].ws',
    },
    [Modes.SD1]: {
        slider1: 'operators[0].tl',
        slider2: 'operators[1].tl',
        slider3: 'operators[2].tl',
        slider4: 'operators[3].tl',
        slider5: 'operators[0].fb',
        slider6: 'operators[1].fb',
        slider7: 'operators[2].fb',
        slider8: 'operators[3].fb',
        knob1: 'operators[0].multi',
        knob2: 'operators[1].multi',
        knob3: 'operators[2].multi',
        knob4: 'operators[3].multi',
        knob5: 'operators[0].dt',
        knob6: 'operators[1].dt',
        knob7: 'operators[2].dt',
        knob8: 'operators[3].dt',
    },
};
